version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    # Only open pull requests for security updates...
    open-pull-requests-limit: 0

  - package-ecosystem: "npm"
    directory: "/packages/core"
    schedule:
      interval: "daily"
    # Only open pull requests for security updates...
    open-pull-requests-limit: 0

  - package-ecosystem: "npm"
    directory: "/packages/alpine"
    schedule:
      interval: "daily"
    # Only open pull requests for security updates...
    open-pull-requests-limit: 0

  - package-ecosystem: "npm"
    directory: "/packages/react"
    schedule:
      interval: "daily"
    # Only open pull requests for security updates...
    open-pull-requests-limit: 0

  - package-ecosystem: "npm"
    directory: "/packages/vue"
    schedule:
      interval: "daily"
    # Only open pull requests for security updates...
    open-pull-requests-limit: 0
